package dev.adokky.eqtester

class EqualsTesterConfigBuilder internal constructor(): EqualsTesterConfig {
    private val groups = ArrayList<TestGroup>()

    override var requireNonIdentical: Boolean = EqualsTesterConfigImpl.Default.requireNonIdentical

    override var maxIterations: Int = EqualsTesterConfigImpl.Default.maxIterations

    override var defaultGroupSize: Int = EqualsTesterConfigImpl.Default.defaultGroupSize

    override var checkToString: Boolean = EqualsTesterConfigImpl.Default.checkToString

    override var checkCollectionContracts: Boolean = EqualsTesterConfigImpl.Default.checkCollectionContracts

    override var checkComparable: Boolean = EqualsTesterConfigImpl.Default.checkComparable

    /**
     * Adds a lazy group of objects generated by a factory function.
     *
     * The factory is invoked [defaultGroupSize] times to produce the group elements.
     *
     * Example:
     * ```
     * testEquality {
     *     group { User("alice") }
     * }
     * ```
     *
     * @see groupOfSize
     * @see namedGroup
     */
    fun group(elementFactory: (index: Int) -> Any) {
        groups.add(TestGroup.Lazy(elementFactory))
    }

    /**
     * Adds a lazy group of a specific size generated by a factory function.
     *
     * @see group
     * @see namedGroup
     */
    fun groupOfSize(size: Int, elementFactory: (index: Int) -> Any) {
        groups.add(TestGroup.Lazy(elementFactory, customSize = size))
    }

    /**
     * Adds a named lazy group.
     *
     * If [size] is `null`, [defaultGroupSize] is used.
     *
     * @see group
     * @see namedGroup
     */
    fun namedGroup(name: String, size: Int? = null, elementFactory: (index: Int) -> Any) {
        groups.add(TestGroup.Lazy(elementFactory, name = name, customSize = size))
    }

    /**
     * Adds a group using a fixed list of objects.
     *
     * @see namedGroup
     */
    fun group(data: List<Any>) {
        groups.add(TestGroup.Simple(data, name = null))
    }

    /**
     * Adds a named group using a fixed list of objects.
     *
     * @see group
     */
    fun namedGroup(name: String, data: List<Any>) {
        groups.add(TestGroup.Simple(data, name))
    }

    /**
     * Adds a group with explicitly provided objects.
     *
     * @see group
     * @see namedGroup
     */
    fun group(element0: Any, element1: Any, vararg rest: Any) {
        group(listOf(element0, element1) + rest)
    }

    /**
     * Adds a named group with explicitly provided objects.
     *
     * @see namedGroup
     * @see group
     */
    fun namedGroup(name: String, element0: Any, element1: Any, vararg rest: Any) {
        namedGroup(name, listOf(element0, element1) + rest)
    }

    @Deprecated("", replaceWith = ReplaceWith("checkCollectionContracts"), level = DeprecationLevel.ERROR)
    var collectionContractCheck: Boolean by ::checkCollectionContracts

    internal fun toConfig() = EqualsTesterConfigImpl(
        groups = groups.apply { forEach { it.init(this@EqualsTesterConfigBuilder) } },
        requireNonIdentical = requireNonIdentical,
        maxIterations = maxIterations,
        checkToString = checkToString,
        checkComparable = checkComparable,
        checkCollectionContracts = checkCollectionContracts
    )
}